version: '3.1'

volumes:
  Config:
  Logs:
  Data:
  gitlab-runner-config:
  apache2_data:

services:
  web:
    image: httpd
    container_name: apache2
    restart: always
    ports:
      - '8080:80'
      - '22000:22'
    volumes:
      - apache2_data:/usr/local/apache2/htdocs/
    stdin_open: true
    tty: true

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    container_name: gitlab
    restart: always
    #hostname: 'gitlab.bassem.com' #CI/CD won't work with hostname
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.1.56'
        #gitlab_rails['gitlab_shell_ssh_port'] = 22
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - Config:/etc/gitlab
      - Logs:/var/log/gitlab
      - Data:/var/opt/gitlab
    

  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner-config:/etc/gitlab-runner



